name: NenoSerpent CMake CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Setup CMake 4.x
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: "4.1.0"

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          ninja-build \
          libgl1-mesa-dev \
          libvulkan-dev \
          libasound2-dev \
          libpulse-dev \
          libsensors-dev \
          xvfb \
          libxcb-cursor0 \
          libxcb-xinerama0 \
          libxcb-icccm4 \
          libxcb-image0 \
          libxcb-keysyms1 \
          libxcb-render-util0 \
          libxcb-shape0 \
          libxkbcommon-x11-0

    - name: Install Qt6
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.7.2' # Upgraded to more stable 6.7 LTS
        host: 'linux'
        target: 'desktop'
        # Added qtsensors to the modules list
        modules: 'qtmultimedia qtshadertools qtsensors'

    - name: Configure CMake
      run: |
        export CC=gcc
        export CXX=g++
        cmake --preset debug --fresh

    - name: Build
      run: cmake --build --preset debug

    - name: Run Tests
      run: |
        export QT_QPA_PLATFORM=offscreen
        xvfb-run -a ctest --preset debug --output-on-failure
